# Generated by Django 3.0.6 on 2020-05-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_title', models.CharField(blank=True, max_length=12, null=True)),
                ('name', models.CharField(help_text='Name', max_length=256)),
                ('surname', models.CharField(max_length=135)),
                ('mail', models.EmailField(max_length=254)),
                ('telephoneNumber', models.CharField(blank=True, max_length=135, null=True)),
                ('common_name', models.CharField(blank=True, help_text='Common Name', max_length=256, null=True)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=128, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=128, null=True)),
                ('tin', models.CharField(help_text="Tax Payer's Number or UniqueID", max_length=16, null=True)),
                ('gender', models.CharField(blank=True, choices=[('0', 'Not know'), ('1', 'Male'), ('2', 'Female'), ('9', 'Not specified')], max_length=3, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('place_of_birth', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Digital Identities',
                'ordering': ['created'],
            },
        ),
    ]
